[package]
name = "mqtt-thingsboard"
version = "0.1.0"
authors = ["Anatol Ulrich <anatol.ulrich@ferrous-systems.com>"]
edition = "2021"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["native"]
native = ["esp-idf-sys/native"]

[dependencies]
esp-idf-sys = { version = "=0.30.4", features = ["binstart"] }
#esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc.git", features = ["experimental", "alloc"], rev="d7313416" }
esp-idf-svc = { version = "=0.36.7", features = ["experimental", "alloc"] }
embedded-svc = "=0.16.5"
esp32-c3-dkc02-bsc = { path = "../../../common/lib/esp32-c3-dkc02-bsc" }
log = "0.4"
anyhow = "1"
toml-cfg = "0.1"
esp32c3 = "0.3.0"
riscv = { version = "0.7", features = ["inline-asm"] }

[build-dependencies]
embuild = "0.28"
anyhow = "1"

[patch.crates-io]
riscv = { git = "https://github.com/rust-embedded/riscv", rev = "396fb9b" }
